name: Build Vite React Tailwind

on:
  push:
    branches:
      - main # Change this to your main branch name if it's different
  pull_request:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: dist # Adjust this path to match your build output directory

    - name: Deploy to production
      if: success() && github.event_name == 'push'
      run: |
        # Your deployment steps go here
        # For example, you might deploy the build to a hosting service.

    - name: Cleanup
      if: always()
      run: npm ci

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
